Vagrant.configure("2") do |config|
  config.vm.define "centos-7n" do |srv|
    srv.vm.box = "centos/7"
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "centos-7n"
      vb.customize ['modifyvm', :id, '--audio', 'none']
    end

    # Подключение дисков
    srv.vm.disk :disk, size: "1GB", name: "disk1"
    srv.vm.disk :disk, size: "1GB", name: "disk2"

    srv.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

    # === ПРОВИЖИН ===
    srv.vm.provision "shell", inline: <<-SHELL
      set -e

      # Дожидаемся пока диски появятся в /dev
      until lsblk | grep -qE "vd[b-c]"; do sleep 1; done

      # форматирование
      mkfs.ext4 -F /dev/vdb
      mkfs.ext4 -F /dev/vdc

      # точки монтирования
      mkdir -p /mnt/disk1
      mkdir -p /mnt/disk2

      # монтирование
      mount /dev/vdb /mnt/disk1
      mount /dev/vdc /mnt/disk2

      # fstab
      grep -q "/mnt/disk1" /etc/fstab || echo "/dev/vdb /mnt/disk1 ext4 defaults 0 0" >> /etc/fstab
      grep -q "/mnt/disk2" /etc/fstab || echo "/dev/vdc /mnt/disk2 ext4 defaults 0 0" >> /etc/fstab
    SHELL
  end
end
